In [1]:
import numpy as np

## Creating numpy array from list

In [2]:
arr_i1 = np.array([1,2,3,4,5])
print("1d array", arr_i1)

arr_i2 = np.array([[1,2,3,4],[5,6,7,8]])
print("2d array", arr_i2)

1d array [1 2 3 4 5]
2d array [[1 2 3 4]
 [5 6 7 8]]


### List vs numpy array

In [3]:
py_list = [1,2,3]
print("Python list multiplication", py_list *2)

Python list multiplication [1, 2, 3, 1, 2, 3]


In [ ]:
np_array = np.array([1,2,3,4]) #element wise multiplication
print("Python a multiplication", np_array *2)


Python a multiplication [2 4 6 8]


In [8]:
import time

start = time.time();

py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy operation time: ",time.time()-start)


 List operation time:  0.058493852615356445

 Numpy operation time:  0.0014247894287109375


### Creating array from scratch


In [ ]:
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)

ones = np.ones((2,3))
print("Ones array: \n",ones)

full = np.full((2,2),7) # 2,2 tuple and 7 is a constant value
print("full array: \n",full)

random = np.random.random((2,3))
print("random array: \n",random)

sequence = np.arange(0,10,2)
print("sequence array: \n",sequence)



zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.56884403 0.68204211 0.87222141]
 [0.70163606 0.71068142 0.21406878]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [13]:
vector = np.array([1,2,3])
print("vector: \n", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix: \n", matrix)

# tensor have multi dimensional array
tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: \n", tensor)


vector: 
 [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
#we can write all data types in the numpy array 
# but for the numpy optimization it is preffered 
# to work with the same data type
print("Shape ",arr.shape)
print("dimension ",arr.ndim)
print("size ",arr.size) # number of elements
print("Data type ",arr.dtype)




Shape  (2, 3)
dimension  2
size  6
Data type  int64


### Array reshaping

In [20]:
arr = np.arange(12)
print("Original array ", arr) 

reshaped = arr.reshape((3,4))
print("Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("Reshaped array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("Reshaped array ", raveled)

# transpose
tranpose = reshaped.T
print("Reshaped array ", tranpose)



Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
