### Phase 2

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing",arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing",arr[-3])


Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [5]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Elements: ",arr_2d[1,2])
print("Entire row: ",arr_2d[1])
# This mean i am targeting entire row
print("Entire row: ",arr_2d[:,1])


Specific Elements:  6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


### Sorting

In [ ]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column",np.sort(arr_2d_unsorted,axis =0))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 3]
 [1 2]
 [2 3]]


### Filter

In [9]:
numbers = np.arange(10)
even_number = numbers[numbers % 2 == 0]
print("Enter numbers", even_number)


Enter numbers [0 2 4 6 8]


### Filter with mask

In [ ]:
mask = numbers>5 # expression is stored as an evaluation
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [6 7 8 9]


### Fancy indexing vs np.where()

In [12]:
indicies = [0,2,4]
print(numbers[indicies])

where_result = np.where(numbers>5)
print(where_result) # array indexing is stored in this
print("NP where", numbers[where_result])


[0 2 4]
(array([6, 7, 8, 9]),)
NP where [6 7 8 9]


In [ ]:
condition_array = np.where(numbers>5,numbers*4,numbers)
condition_array = np.where(numbers>5,"true","false")
print(condition_array)
# if(numbers>5){
#     numbers * 4
# }else{
#     numbers
# }

['false' 'false' 'false' 'false' 'false' 'false' 'true' 'true' 'true'
 'true']


### Adding and removing data

In [15]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)




[1 2 3 4 5 6]


### array compatibility

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibilty shapes", a.shape==b.shape)

Compatibilty shapes True


In [18]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row))

print("original: \n",original)
print("With new row: \n",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("original: \n",original)
print("With new col: \n",with_new_col)


original: 
 [[1 2]
 [3 4]]
With new row: 
 [[1 2]
 [3 4]
 [5 6]]
original: 
 [[1 2]
 [3 4]]
With new col: 
 [[1 2 7]
 [3 4 8]]


In [ ]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion:", deleted) # this will give us the deleted array

Array after deletion [1 2 4 5]
